server:
  port: 8091
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/magicdoc_view?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: ilxw
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 50
      max-wait: 10000
      min-idle: 5
      initial-size: 5
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:mapper/*DAO.xml
  type-aliases-package: cn.javayong..sms.domain

